### ISSUE TITLE
Better input handling

### ISSUE THREAD

**Issue by chocolate42** [chocolate42/flaccid#1]
It's very limited, 16 bit only and bit rot has set in

- [x] Read input as it's needed instead of completely before encode begins. Large overhaul required
- [x] Fix or remove raw input
- [ ] #6
- [x] Input pipe support
- [x] #5
- [x] Once input is overhauled MD5 can be done on ingest

**Comment by ktmf01** [comment]
I don't know what you use the raw input for, but if you'd rather want WAV but don't want all the processing that comes with it, maybe consider using dr_wav: https://github.com/mackron/dr_libs

**Comment by chocolate42** [comment]
Thanks. Raw input was the first thing hastily implemented to be able to test at all, but it's such a pain to deal with that flac input came soon after. Might ditch raw input or match the ./flac interface. dr_wav looks good, will probably implement wav using it when some other issues about input have been resolved.

**Comment by chocolate42** [comment]
TODO in priority order
- Read input as it's needed instead of completely before encode begins. Large overhaul required
- Fix or remove raw input
- use dr_wav to implement wav input
- Input pipe support
- Output pipe is supportable but would require the entire output to be cached until the header has been updated. Shouldn't be an issue for the vast majority of use cases

**Comment by chocolate42** [comment]
A real use case for raw input is handling audio from CD video game rips, the standard there is to store the tracks as multiple-bin+cue where the data is raw 2352 and the audio is raw CDDA. So I think I'll support that and no other raw input and call it good, no one else should really have a major need to handle raw. Even if they do they could do something like have ./flac pipe it in to ./flaccid so flaccid sees a flac file.
